version: '3'

services:
  maildev:
    image: maildev/maildev
    ports:
      - '1025:25'
      - '1080:80'
    environment:
      MAILDEV_INCOMING_USER: username
      MAILDEV_INCOMING_PASS: password
